[theme]
primaryColor = "#5A8766"
backgroundColor = "#D9F4DA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0F172A"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
